module.exports={
    devServer:{
        open:true,
        port:8080,
        host:"localhost",
        proxy:{
            "^/ele":{
                target:"http://localhost:8088",
                changeOrigin:true,
                pathRewrite:{
                    "^/ele":""
                }
            }
        }
    }
}